import type { Metadata } from "next";
import NavBar from "../components/nav-bar";
import Sidebar from "../components/sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex relative">
        <Sidebar />
        <div className="w-full ">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
